<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYHI3L6H\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYHI3L6H/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerYHI3L6H.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerYHI3L6H\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerYHI3L6H\appAppKernelProdContainer([
    'container.build_hash' => 'YHI3L6H',
    'container.build_id' => '539c021a',
    'container.build_time' => 1750709405,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYHI3L6H');
