<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHwQFjxn\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHwQFjxn/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerHwQFjxn.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerHwQFjxn\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerHwQFjxn\appAppKernelProdContainer([
    'container.build_hash' => 'HwQFjxn',
    'container.build_id' => '85429941',
    'container.build_time' => 1749151766,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHwQFjxn');
