<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIN8dTwv\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIN8dTwv/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerIN8dTwv.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerIN8dTwv\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerIN8dTwv\appAppKernelProdContainer([
    'container.build_hash' => 'IN8dTwv',
    'container.build_id' => '2b2ac9c0',
    'container.build_time' => 1750193401,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIN8dTwv');
